### ISSUE TITLE
mita label parsing should be strict

### ISSUE THREAD

**Issue by andrewschoen** [ceph/mita#66]
Currently, mita will match a subset of labels defined for a job when trying to select a node to spin up for a job. However, this should be a strict match and not a partial one. This became an issue today when we had a job stuck looking for `huge && (ceph-build-xenial) && rebootable`. Mita selected a `precise_huge` node to spin up because it was matching `huge && rebootable`, however jenkins would not select that new node because it doesn't allow a node to be used if it only matches a subset of the labels a job requires. Because of this issue we had many new precise slaves added that were never utilized.

**Comment by dmick** [comment]
I'm in process on a different matcher.  Definitely the slave that mita picks has to supply at least a superset of the required labels.
